package logicElements.effector;

import com.corundumstudio.socketio.SocketIOServer;
import de.mannheim.wifo2.fesas.logicRepositoryStructure.data.metadata.logic.AbstractLogic;
import de.mannheim.wifo2.fesas.logicRepositoryStructure.data.metadata.logic.LogicType;
import de.mannheim.wifo2.fesas.logicRepositoryStructure.data.metadata.logic.logicInterfaces.IEffectorLogic;
import de.mannheim.wifo2.fesas.sasStructure.data.adaptationLogic.information.InformationType;
import de.mannheim.wifo2.fesas.sasStructure.data.adaptationLogic.knowledge.IKnowledgeRecord;
import de.mannheim.wifo2.fesas.sasStructure.data.adaptationLogic.knowledge.KnowledgeRecord;
import dependencies.SocketManager;

import java.util.HashMap;

/**
 * Description from meta data:
 * <p>
 * This file has been generated by the FESAS development tool set.
 *
 * @author FESAS
 */
public class SocketIoEffector extends AbstractLogic implements IEffectorLogic {

    public SocketIoEffector() {
        super();
        supportedInformationTypes.add(InformationType.Executing_DEFAULT);

        this.informationType = InformationType.Effector_DEFAULT;
        type = LogicType.EFFECTOR;
        shortName = "SocketIoEffector";
    }

    // do not change anything above this line (except of adding import statements)

    //add variables here
    private SocketIOServer server;

    @Override
    public void initializeLogic(HashMap<String, String> properties) {
        server = SocketManager.getInstance().getServer();
    }

    @Override
    public String callLogic(IKnowledgeRecord data) {
        if (data instanceof KnowledgeRecord) {
            if (data.getData() instanceof String) {

                // Send data to all clients connected to the FESAS System
                server.getAllClients().forEach(client -> client.sendEvent("effectorData", data.getData()));

            }
            return "Not the expected data type! It is: " + data.getData().getClass().getSimpleName();
        }
        return "Not a KnowledgeRecord! It is: " + data.getClass().getSimpleName();
    }

    // add further methods if needed

}
